import "./globals.css";
import { Mulish, Roboto } from "next/font/google";
import Header from "./components/Header";

const mulish = Mulish({ subsets: ["latin"], weight: "500", display: "swap" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
