import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import Myprofile from "./components/myprofile";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "ali ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar />
        <Myprofile />
        {children}
      </body>
    </html>
  );
}
